"""current schema baseline

Revision ID: 5e3799a70fb6
Revises: 
Create Date: 2026-09-26 19:12:13.094558
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5e3799a70fb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('last_failed_at', sa.DateTime(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'ip_address', name='uq_auth_rate_limits_username_ip')
    )
    op.create_index(op.f('ix_auth_rate_limits_blocked_until'), 'auth_rate_limits', ['blocked_until'], unique=False)
    op.create_index(op.f('ix_auth_rate_limits_id'), 'auth_rate_limits', ['id'], unique=False)
    op.create_index(op.f('ix_auth_rate_limits_ip_address'), 'auth_rate_limits', ['ip_address'], unique=False)
    op.create_index(op.f('ix_auth_rate_limits_username'), 'auth_rate_limits', ['username'], unique=False)
    op.create_table('development_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_development_stages_code'), 'development_stages', ['code'], unique=True)
    op.create_index(op.f('ix_development_stages_id'), 'development_stages', ['id'], unique=False)
    op.create_index(op.f('ix_development_stages_is_active'), 'development_stages', ['is_active'], unique=False)
    op.create_index(op.f('ix_development_stages_position'), 'development_stages', ['position'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('robot_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['robot_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_folders_id'), 'robot_folders', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vault_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['vault_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_folders_id'), 'vault_folders', ['id'], unique=False)
    op.create_table('development_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['development_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_development_folders_created_by'), 'development_folders', ['created_by'], unique=False)
    op.create_index(op.f('ix_development_folders_id'), 'development_folders', ['id'], unique=False)
    op.create_index(op.f('ix_development_folders_parent_id'), 'development_folders', ['parent_id'], unique=False)
    op.create_table('library_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['library_folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_folders_created_by'), 'library_folders', ['created_by'], unique=False)
    op.create_index(op.f('ix_library_folders_id'), 'library_folders', ['id'], unique=False)
    op.create_index(op.f('ix_library_folders_is_active'), 'library_folders', ['is_active'], unique=False)
    op.create_index(op.f('ix_library_folders_name'), 'library_folders', ['name'], unique=False)
    op.create_index(op.f('ix_library_folders_parent_id'), 'library_folders', ['parent_id'], unique=False)
    op.create_table('robots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['robot_folders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_id'), 'robots', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_access_token'), 'user_sessions', ['access_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('vault_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('credential_type', sa.String(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['vault_folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_credentials_credential_type'), 'vault_credentials', ['credential_type'], unique=False)
    op.create_index(op.f('ix_vault_credentials_folder_id'), 'vault_credentials', ['folder_id'], unique=False)
    op.create_index(op.f('ix_vault_credentials_id'), 'vault_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_vault_credentials_scope'), 'vault_credentials', ['scope'], unique=False)
    op.create_table('agents',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_token_hash', sa.String(length=64), nullable=False),
    sa.Column('agent_token_encrypted', sa.Text(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('rpa_directory', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('session_status', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('execution_username', sa.String(), nullable=True),
    sa.Column('execution_domain', sa.String(), nullable=True),
    sa.Column('execution_credential_id', sa.Integer(), nullable=True),
    sa.Column('display_width', sa.Integer(), nullable=False),
    sa.Column('display_height', sa.Integer(), nullable=False),
    sa.Column('display_scale', sa.Integer(), nullable=False),
    sa.Column('display_current_width', sa.Integer(), nullable=True),
    sa.Column('display_current_height', sa.Integer(), nullable=True),
    sa.Column('display_supported', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['execution_credential_id'], ['vault_credentials.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agents_agent_token_hash'), 'agents', ['agent_token_hash'], unique=True)
    op.create_index(op.f('ix_agents_environment'), 'agents', ['environment'], unique=False)
    op.create_index(op.f('ix_agents_execution_credential_id'), 'agents', ['execution_credential_id'], unique=False)
    op.create_table('automation_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_stage_id', sa.Integer(), nullable=True),
    sa.Column('base_robot_id', sa.Integer(), nullable=True),
    sa.Column('base_robot_name', sa.String(), nullable=True),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('functional_responsible_id', sa.Integer(), nullable=True),
    sa.Column('technical_responsible_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('effort_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_robot_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_stage_id'], ['development_stages.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['development_folders.id'], ),
    sa.ForeignKeyConstraint(['functional_responsible_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technical_responsible_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_projects_base_robot_id'), 'automation_projects', ['base_robot_id'], unique=False)
    op.create_index(op.f('ix_automation_projects_created_by'), 'automation_projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_automation_projects_current_stage_id'), 'automation_projects', ['current_stage_id'], unique=False)
    op.create_index(op.f('ix_automation_projects_deleted_at'), 'automation_projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_automation_projects_deleted_by'), 'automation_projects', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_automation_projects_folder_id'), 'automation_projects', ['folder_id'], unique=False)
    op.create_index(op.f('ix_automation_projects_functional_responsible_id'), 'automation_projects', ['functional_responsible_id'], unique=False)
    op.create_index(op.f('ix_automation_projects_id'), 'automation_projects', ['id'], unique=False)
    op.create_index(op.f('ix_automation_projects_is_active'), 'automation_projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_automation_projects_name'), 'automation_projects', ['name'], unique=False)
    op.create_index(op.f('ix_automation_projects_status'), 'automation_projects', ['status'], unique=False)
    op.create_index(op.f('ix_automation_projects_technical_responsible_id'), 'automation_projects', ['technical_responsible_id'], unique=False)
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('import_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('production_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['library_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_version_id'], ['library_versions.id'], name='fk_libraries_production_version_id_library_versions', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libraries_created_by'), 'libraries', ['created_by'], unique=False)
    op.create_index(op.f('ix_libraries_folder_id'), 'libraries', ['folder_id'], unique=False)
    op.create_index(op.f('ix_libraries_id'), 'libraries', ['id'], unique=False)
    op.create_index(op.f('ix_libraries_import_name'), 'libraries', ['import_name'], unique=True)
    op.create_index(op.f('ix_libraries_is_active'), 'libraries', ['is_active'], unique=False)
    op.create_index(op.f('ix_libraries_name'), 'libraries', ['name'], unique=False)
    op.create_index(op.f('ix_libraries_production_version_id'), 'libraries', ['production_version_id'], unique=False)
    op.create_table('vault_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('encryption_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['vault_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_fields_id'), 'vault_fields', ['id'], unique=False)
    op.create_table('library_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_robot_id', sa.Integer(), nullable=True),
    sa.Column('source_robot_version', sa.Integer(), nullable=True),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('published_by', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'version', name='uq_library_versions_library_version')
    )
    op.create_index(op.f('ix_library_versions_id'), 'library_versions', ['id'], unique=False)
    op.create_index(op.f('ix_library_versions_is_active'), 'library_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_library_versions_library_id'), 'library_versions', ['library_id'], unique=False)
    op.create_index(op.f('ix_library_versions_published_at'), 'library_versions', ['published_at'], unique=False)
    op.create_index(op.f('ix_library_versions_published_by'), 'library_versions', ['published_by'], unique=False)
    op.create_index(op.f('ix_library_versions_source_robot_id'), 'library_versions', ['source_robot_id'], unique=False)
    op.create_index(op.f('ix_library_versions_source_type'), 'library_versions', ['source_type'], unique=False)
    op.create_index(op.f('ix_library_versions_version'), 'library_versions', ['version'], unique=False)
    op.create_foreign_key(
        'fk_libraries_production_version_id_library_versions',
        'libraries',
        'library_versions',
        ['production_version_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('project_checkouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['automation_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_project_checkouts_id'), 'project_checkouts', ['id'], unique=False)
    op.create_index(op.f('ix_project_checkouts_user_id'), 'project_checkouts', ['user_id'], unique=False)
    op.create_table('project_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['automation_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_comments_created_at'), 'project_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_comments_id'), 'project_comments', ['id'], unique=False)
    op.create_index(op.f('ix_project_comments_project_id'), 'project_comments', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_comments_user_id'), 'project_comments', ['user_id'], unique=False)
    op.create_table('project_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=True),
    sa.Column('to_stage_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_stage_id'], ['development_stages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['automation_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_stage_id'], ['development_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_stage_history_changed_at'), 'project_stage_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_project_stage_history_changed_by'), 'project_stage_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_project_stage_history_from_stage_id'), 'project_stage_history', ['from_stage_id'], unique=False)
    op.create_index(op.f('ix_project_stage_history_id'), 'project_stage_history', ['id'], unique=False)
    op.create_index(op.f('ix_project_stage_history_project_id'), 'project_stage_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_stage_history_to_stage_id'), 'project_stage_history', ['to_stage_id'], unique=False)
    op.create_table('robot_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('artifact_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('source_project_id', sa.Integer(), nullable=True),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_project_id'], ['automation_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'version', name='uq_robot_versions_robot_version')
    )
    op.create_index(op.f('ix_robot_versions_created_at'), 'robot_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_robot_versions_id'), 'robot_versions', ['id'], unique=False)
    op.create_index(op.f('ix_robot_versions_published_at'), 'robot_versions', ['published_at'], unique=False)
    op.create_index(op.f('ix_robot_versions_published_by'), 'robot_versions', ['published_by'], unique=False)
    op.create_index(op.f('ix_robot_versions_robot_id'), 'robot_versions', ['robot_id'], unique=False)
    op.create_index(op.f('ix_robot_versions_source_project_id'), 'robot_versions', ['source_project_id'], unique=False)
    op.create_index(op.f('ix_robot_versions_version'), 'robot_versions', ['version'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('horario', sa.String(), nullable=False),
    sa.Column('dias_semana', sa.String(), nullable=True),
    sa.Column('intervalo_ativo', sa.Integer(), nullable=False),
    sa.Column('intervalo_valor', sa.Integer(), nullable=True),
    sa.Column('intervalo_unidade', sa.String(), nullable=True),
    sa.Column('horario_fim', sa.String(), nullable=True),
    sa.Column('ativo', sa.Integer(), nullable=False),
    sa.Column('proxima_execucao', sa.DateTime(), nullable=True),
    sa.Column('ultima_execucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('robot_version', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('robot_name', sa.String(), nullable=False),
    sa.Column('robot_filename', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('schedule_run_id', sa.String(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['automation_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_id'), 'executions', ['id'], unique=False)
    op.create_index(op.f('ix_executions_project_id'), 'executions', ['project_id'], unique=False)
    op.create_index(op.f('ix_executions_robot_version'), 'executions', ['robot_version'], unique=False)
    op.create_index(op.f('ix_executions_schedule_id'), 'executions', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_executions_schedule_run_id'), 'executions', ['schedule_run_id'], unique=True)
    op.create_index(op.f('ix_executions_source_type'), 'executions', ['source_type'], unique=False)
    op.create_index(op.f('ix_executions_user_id'), 'executions', ['user_id'], unique=False)
    op.create_table('project_library_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('library_version_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['library_version_id'], ['library_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['automation_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'library_id', name='uq_project_library_dependencies_project_library')
    )
    op.create_index(op.f('ix_project_library_dependencies_added_by'), 'project_library_dependencies', ['added_by'], unique=False)
    op.create_index(op.f('ix_project_library_dependencies_id'), 'project_library_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_project_library_dependencies_library_id'), 'project_library_dependencies', ['library_id'], unique=False)
    op.create_index(op.f('ix_project_library_dependencies_library_version_id'), 'project_library_dependencies', ['library_version_id'], unique=False)
    op.create_index(op.f('ix_project_library_dependencies_project_id'), 'project_library_dependencies', ['project_id'], unique=False)
    op.create_table('project_library_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('base_library_version_id', sa.Integer(), nullable=True),
    sa.Column('workspace_path', sa.String(), nullable=False),
    sa.Column('is_modified', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_library_version_id'], ['library_versions.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['automation_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'library_id', name='uq_project_library_drafts_project_library')
    )
    op.create_index(op.f('ix_project_library_drafts_base_library_version_id'), 'project_library_drafts', ['base_library_version_id'], unique=False)
    op.create_index(op.f('ix_project_library_drafts_created_by'), 'project_library_drafts', ['created_by'], unique=False)
    op.create_index(op.f('ix_project_library_drafts_id'), 'project_library_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_project_library_drafts_is_modified'), 'project_library_drafts', ['is_modified'], unique=False)
    op.create_index(op.f('ix_project_library_drafts_library_id'), 'project_library_drafts', ['library_id'], unique=False)
    op.create_index(op.f('ix_project_library_drafts_project_id'), 'project_library_drafts', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_library_drafts_updated_by'), 'project_library_drafts', ['updated_by'], unique=False)
    op.create_table('robot_version_library_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('robot_version', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('library_version_id', sa.Integer(), nullable=False),
    sa.Column('source_project_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['library_version_id'], ['library_versions.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['source_project_id'], ['automation_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'robot_version', 'library_id', name='uq_robot_version_library_dependencies_robot_version_library')
    )
    op.create_index(op.f('ix_robot_version_library_dependencies_created_at'), 'robot_version_library_dependencies', ['created_at'], unique=False)
    op.create_index(op.f('ix_robot_version_library_dependencies_created_by'), 'robot_version_library_dependencies', ['created_by'], unique=False)
    op.create_index(op.f('ix_robot_version_library_dependencies_id'), 'robot_version_library_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_robot_version_library_dependencies_library_id'), 'robot_version_library_dependencies', ['library_id'], unique=False)
    op.create_index(op.f('ix_robot_version_library_dependencies_library_version_id'), 'robot_version_library_dependencies', ['library_version_id'], unique=False)
    op.create_index(op.f('ix_robot_version_library_dependencies_robot_id'), 'robot_version_library_dependencies', ['robot_id'], unique=False)
    op.create_index(op.f('ix_robot_version_library_dependencies_robot_version'), 'robot_version_library_dependencies', ['robot_version'], unique=False)
    op.create_index(op.f('ix_robot_version_library_dependencies_source_project_id'), 'robot_version_library_dependencies', ['source_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_libraries_production_version_id_library_versions',
        'libraries',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_robot_version_library_dependencies_source_project_id'), table_name='robot_version_library_dependencies')
    op.drop_index(op.f('ix_robot_version_library_dependencies_robot_version'), table_name='robot_version_library_dependencies')
    op.drop_index(op.f('ix_robot_version_library_dependencies_robot_id'), table_name='robot_version_library_dependencies')
    op.drop_index(op.f('ix_robot_version_library_dependencies_library_version_id'), table_name='robot_version_library_dependencies')
    op.drop_index(op.f('ix_robot_version_library_dependencies_library_id'), table_name='robot_version_library_dependencies')
    op.drop_index(op.f('ix_robot_version_library_dependencies_id'), table_name='robot_version_library_dependencies')
    op.drop_index(op.f('ix_robot_version_library_dependencies_created_by'), table_name='robot_version_library_dependencies')
    op.drop_index(op.f('ix_robot_version_library_dependencies_created_at'), table_name='robot_version_library_dependencies')
    op.drop_table('robot_version_library_dependencies')
    op.drop_index(op.f('ix_project_library_drafts_updated_by'), table_name='project_library_drafts')
    op.drop_index(op.f('ix_project_library_drafts_project_id'), table_name='project_library_drafts')
    op.drop_index(op.f('ix_project_library_drafts_library_id'), table_name='project_library_drafts')
    op.drop_index(op.f('ix_project_library_drafts_is_modified'), table_name='project_library_drafts')
    op.drop_index(op.f('ix_project_library_drafts_id'), table_name='project_library_drafts')
    op.drop_index(op.f('ix_project_library_drafts_created_by'), table_name='project_library_drafts')
    op.drop_index(op.f('ix_project_library_drafts_base_library_version_id'), table_name='project_library_drafts')
    op.drop_table('project_library_drafts')
    op.drop_index(op.f('ix_project_library_dependencies_project_id'), table_name='project_library_dependencies')
    op.drop_index(op.f('ix_project_library_dependencies_library_version_id'), table_name='project_library_dependencies')
    op.drop_index(op.f('ix_project_library_dependencies_library_id'), table_name='project_library_dependencies')
    op.drop_index(op.f('ix_project_library_dependencies_id'), table_name='project_library_dependencies')
    op.drop_index(op.f('ix_project_library_dependencies_added_by'), table_name='project_library_dependencies')
    op.drop_table('project_library_dependencies')
    op.drop_index(op.f('ix_executions_user_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_source_type'), table_name='executions')
    op.drop_index(op.f('ix_executions_schedule_run_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_schedule_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_robot_version'), table_name='executions')
    op.drop_index(op.f('ix_executions_project_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_robot_versions_version'), table_name='robot_versions')
    op.drop_index(op.f('ix_robot_versions_source_project_id'), table_name='robot_versions')
    op.drop_index(op.f('ix_robot_versions_robot_id'), table_name='robot_versions')
    op.drop_index(op.f('ix_robot_versions_published_by'), table_name='robot_versions')
    op.drop_index(op.f('ix_robot_versions_published_at'), table_name='robot_versions')
    op.drop_index(op.f('ix_robot_versions_id'), table_name='robot_versions')
    op.drop_index(op.f('ix_robot_versions_created_at'), table_name='robot_versions')
    op.drop_table('robot_versions')
    op.drop_index(op.f('ix_project_stage_history_to_stage_id'), table_name='project_stage_history')
    op.drop_index(op.f('ix_project_stage_history_project_id'), table_name='project_stage_history')
    op.drop_index(op.f('ix_project_stage_history_id'), table_name='project_stage_history')
    op.drop_index(op.f('ix_project_stage_history_from_stage_id'), table_name='project_stage_history')
    op.drop_index(op.f('ix_project_stage_history_changed_by'), table_name='project_stage_history')
    op.drop_index(op.f('ix_project_stage_history_changed_at'), table_name='project_stage_history')
    op.drop_table('project_stage_history')
    op.drop_index(op.f('ix_project_comments_user_id'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_project_id'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_id'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_created_at'), table_name='project_comments')
    op.drop_table('project_comments')
    op.drop_index(op.f('ix_project_checkouts_user_id'), table_name='project_checkouts')
    op.drop_index(op.f('ix_project_checkouts_id'), table_name='project_checkouts')
    op.drop_table('project_checkouts')
    op.drop_index(op.f('ix_library_versions_version'), table_name='library_versions')
    op.drop_index(op.f('ix_library_versions_source_type'), table_name='library_versions')
    op.drop_index(op.f('ix_library_versions_source_robot_id'), table_name='library_versions')
    op.drop_index(op.f('ix_library_versions_published_by'), table_name='library_versions')
    op.drop_index(op.f('ix_library_versions_published_at'), table_name='library_versions')
    op.drop_index(op.f('ix_library_versions_library_id'), table_name='library_versions')
    op.drop_index(op.f('ix_library_versions_is_active'), table_name='library_versions')
    op.drop_index(op.f('ix_library_versions_id'), table_name='library_versions')
    op.drop_table('library_versions')
    op.drop_index(op.f('ix_vault_fields_id'), table_name='vault_fields')
    op.drop_table('vault_fields')
    op.drop_index(op.f('ix_libraries_production_version_id'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_name'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_is_active'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_import_name'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_id'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_folder_id'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_created_by'), table_name='libraries')
    op.drop_table('libraries')
    op.drop_index(op.f('ix_automation_projects_technical_responsible_id'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_status'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_name'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_is_active'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_id'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_functional_responsible_id'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_folder_id'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_deleted_by'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_deleted_at'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_current_stage_id'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_created_by'), table_name='automation_projects')
    op.drop_index(op.f('ix_automation_projects_base_robot_id'), table_name='automation_projects')
    op.drop_table('automation_projects')
    op.drop_index(op.f('ix_agents_execution_credential_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_environment'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_token_hash'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_vault_credentials_scope'), table_name='vault_credentials')
    op.drop_index(op.f('ix_vault_credentials_id'), table_name='vault_credentials')
    op.drop_index(op.f('ix_vault_credentials_folder_id'), table_name='vault_credentials')
    op.drop_index(op.f('ix_vault_credentials_credential_type'), table_name='vault_credentials')
    op.drop_table('vault_credentials')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_access_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_robots_id'), table_name='robots')
    op.drop_table('robots')
    op.drop_index(op.f('ix_library_folders_parent_id'), table_name='library_folders')
    op.drop_index(op.f('ix_library_folders_name'), table_name='library_folders')
    op.drop_index(op.f('ix_library_folders_is_active'), table_name='library_folders')
    op.drop_index(op.f('ix_library_folders_id'), table_name='library_folders')
    op.drop_index(op.f('ix_library_folders_created_by'), table_name='library_folders')
    op.drop_table('library_folders')
    op.drop_index(op.f('ix_development_folders_parent_id'), table_name='development_folders')
    op.drop_index(op.f('ix_development_folders_id'), table_name='development_folders')
    op.drop_index(op.f('ix_development_folders_created_by'), table_name='development_folders')
    op.drop_table('development_folders')
    op.drop_index(op.f('ix_vault_folders_id'), table_name='vault_folders')
    op.drop_table('vault_folders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_robot_folders_id'), table_name='robot_folders')
    op.drop_table('robot_folders')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_development_stages_position'), table_name='development_stages')
    op.drop_index(op.f('ix_development_stages_is_active'), table_name='development_stages')
    op.drop_index(op.f('ix_development_stages_id'), table_name='development_stages')
    op.drop_index(op.f('ix_development_stages_code'), table_name='development_stages')
    op.drop_table('development_stages')
    op.drop_index(op.f('ix_auth_rate_limits_username'), table_name='auth_rate_limits')
    op.drop_index(op.f('ix_auth_rate_limits_ip_address'), table_name='auth_rate_limits')
    op.drop_index(op.f('ix_auth_rate_limits_id'), table_name='auth_rate_limits')
    op.drop_index(op.f('ix_auth_rate_limits_blocked_until'), table_name='auth_rate_limits')
    op.drop_table('auth_rate_limits')
    # ### end Alembic commands ###
